[package]
name = "vk-cli-player"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
inquire = "0.7"
urlencoding = "2.1"
url = "2.5"          # <--- НОВАЯ: для парсинга URL
webbrowser = "1.0"   # <--- НОВАЯ: для открытия браузера
